# Generated by Django 2.2.16 on 2020-09-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='nutritionalValue',
            field=models.TextField(blank=True),
        ),
    ]
