# Generated by Django 2.2.15 on 2020-09-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_auto_20200908_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('massa', 'Massa'), ('pizza', 'Pizza'), ('seafood', 'Fruto do Mar'), ('chinese', 'Chinês'), ('soda', 'Refrigerante'), ('wine', 'Vinho')], max_length=10),
        ),
    ]
