# Generated by Django 2.2.16 on 2020-09-15 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderTable', models.CharField(max_length=6)),
                ('orderNumber', models.CharField(max_length=6)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('situation', models.CharField(choices=[('waiting', 'Esperando'), ('making', 'Preparando'), ('made', 'Pronto')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('dishes', models.ForeignKey(on_delete=None, to='dish.Dish')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
    ]
