# Generated by Django 2.2.16 on 2020-09-12 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderTable', models.CharField(default='xl8Rt5', max_length=6, unique=True)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('dishes', models.ManyToManyField(related_name='dishes', to='dish.Dish')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
    ]
