# Generated by Django 2.2.16 on 2020-09-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTable',
            field=models.CharField(max_length=6),
        ),
    ]
