# Generated by Django 2.2.15 on 2020-09-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_auto_20200908_2038'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(related_name='dishes', to='dish.Dish'),
        ),
    ]
