# Generated by Django 2.2.16 on 2020-09-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dishes',
            new_name='dish',
        ),
    ]
