# Generated by Django 2.2.15 on 2020-09-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='codigo',
        ),
    ]
