# Generated by Django 2.2.15 on 2020-09-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='order',
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('massa', 'Massa'), ('pizza', 'Pizza'), ('seafood', 'Fruto do Mar'), ('chinese', 'Chinês')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
