# Generated by Django 2.2.15 on 2020-09-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=11)),
                ('codigo', models.CharField(max_length=8)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.Menu')),
            ],
        ),
    ]
